### PR TITLE
2.8.0

### PR DESCRIPTION
**Pull request by adlarkin**
Signed-off-by: Ashton Larkin <ashton@openrobotics.org>

# 🎈 Release

Preparation for 2.8.0 release.

Comparison to 2.7.0: https://github.com/ignitionrobotics/ign-cmake/compare/ignition-cmake2_2.7.0...ign-cmake2

## Checklist
- [x] Asked team if this is a good time for a release
- [x] There are no changes to be ported from the previous major version
- [x] No PRs targeted at this major version are close to getting in
- [x] Bumped minor for new features, patch for bug fixes
- [x] Updated changelog
- [x] Updated migration guide (as needed)
- [ ] Link to PR updating dependency versions in appropriate repository in [ignition-release](https://github.com/ignition-release) (as needed): <LINK>

**Note to maintainers**: Remember to use **Squash-Merge**

### CODE REVIEW

**Review by mjcarroll — APPROVED** [review]

**Comment by mjcarroll** [comment]
Have you done a build across the whole stack to see if this breaks anything?

**Comment by chapulina** [comment]
It would be great to include #168 into this release

**Comment by adlarkin** [comment]
#168 should now be included :grinning:

**Review by chapulina — APPROVED** [review]
The test build using skip is warning-free! :ship: it!

https://github.com/ignition-tooling/release-tools/pull/456#issuecomment-831501129

**Review by j-rivero — APPROVED** [review]
we are good to go, I think.

**Comment by adlarkin** [comment]
Windows is failing - I believe the machine might be down? Should we still merge this, or try to resolve windows first?

**Comment by adlarkin** [comment]
All checks pass now; merging!

**Pull request merged**
