### PR TITLE
Port codecov to new configuration

### PR DESCRIPTION
**Pull request by j-rivero**
See https://github.com/ignition-tooling/action-ignition-ci/pull/32/

Signed-off-by: Jose Luis Rivero <jrivero@osrfoundation.org>

### CODE REVIEW

**Comment by adlarkin** [comment]
Would it be worth merging this and then forward porting it to `main` instead of having a separate PR (#169) for `main`?

**Comment by adlarkin** [comment]
I'm also seeing a failure in GitHub actions:
```
make: *** No rule to make target 'coverage'.  Stop.
```

**Comment by adlarkin** [comment]
@j-rivero friendly ping

**Comment by j-rivero** [comment]
> @j-rivero friendly ping

thanks! I've disabled codecov, if I'm not wrong there is no support in this repository for it

**Review by adlarkin — APPROVED** [review]
> I've disabled codecov, if I'm not wrong there is no support in this repository for it

All checks pass, so I'm approving this :+1: @scpeters or @chapulina, beofre we merge this, can one of you confirm that disabling codecov in this repository is okay?

**Comment by chapulina** [comment]
> disabling codecov in this repository is okay?

Yup, I think it should be ok because we aren't generating coverage data either for the tests in `examples` nor the tests in `test`. Not sure if there would be an easy way of adding coverage for CMake files, and I think we shouldn't bother with the utilities C++ code since that's being moved to `ign-utils`.

**Comment by adlarkin** [comment]
Sounds good :+1: merging!

**Pull request merged**
