### PR TITLE
[ign ➡️  gz] Internal parsed variables

### PR DESCRIPTION
**Pull request by chapulina**
* Part of https://github.com/ignition-tooling/release-tools/issues/719

## Summary

This PR updates just the variables parsed by `cmake_parse_arguments` to use `gz` instead of `ign`. Those variables are internal to each function and shouldn't affect the public API.

⬅️ This PR can be backported to `ign-cmake2` later to reduce the diff between the branches.

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [x] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [x] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [x] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸

### CODE REVIEW

**Comment by methylDragon** [comment]
A test build of packages up to `ignition-transport12` failed with this version of CMake3, throwing...

<details>
  <summary>This error</summary>
image

</details>

I'm not sure what's up, but it might be something wonky with macro substitutions, or worse.., an erroneous macro-set variable that bubbles up into the parent scope.

**Review by methylDragon — CHANGES_REQUESTED** [review]
https://github.com/ignitionrobotics/ign-cmake/pull/245/files#diff-955d1f97e2360702839ba9277cc71b9797e65d417d5cb88f383fec0e53ad5124R1000
Found it! Line 1000:
`_ign_handle_cxx_standard(ign_create_core_library` -> `_ign_handle_cxx_standard(gz_create_core_library`

(:

_ign_handle_cxx_standard is a macro that looks for a prefix, not a macro/function name, so we just need to pass in that prefix so it can resolve the appropriate arg!

It builds! (The stderr from math is just the overlay/override check, no worries on that.)
image

**Comment by chapulina** [comment]
> Found it! Line 1000:

Thanks! Well spotted! Committed in [e897659](https://github.com/ignitionrobotics/ign-cmake/pull/245/commits/e897659f8808a39596ff17377b5cdcdb6584fac1)

**Review by methylDragon — APPROVED** [review]
:+1: pending green CI

**Pull request merged**
